import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { Skeleton } from "@/components/ui/skeleton";
import Providers from "@/components/Providers/LayoutProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




const inter = Inter({
  subsets: ["latin"],
  variable: "--inter-font",
  display: "swap",
});


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const rawBaseUrl = process.env.NEXT_PUBLIC_BASE_FRONTEND_DOMAIN || "https://auth-module-3nbt.vercel.app";
  const normalizedBase = rawBaseUrl.startsWith("http") ? rawBaseUrl : `https://${rawBaseUrl.replace(/\/+$/, '')}`;
  const baseUrl = normalizedBase.replace(/\/+$/, '');
  const canonicalUrl = `${baseUrl}`;


  return (
    <html lang="en"
      dir="ltr"
      suppressHydrationWarning
    >
      <head>
        <link rel="icon" href="/favicon.ico" />
        {/* Preconnect to external domains */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://www.youtube.com" />
        <link rel="preconnect" href="https://www.facebook.com" />
        <link rel="preconnect" href="https://instagram.com" />

        <link rel="canonical" href={canonicalUrl} />
        <link rel="alternate" hrefLang="en" href={`${baseUrl}`} />
        <link rel="alternate" hrefLang="x-default" href={`${baseUrl}`} />

        {/* DNS prefetch for performance */}
        <link rel="dns-prefetch" href="https://www.google-analytics.com" />

      </head>
      <body className={`antialiased ${inter.variable}  bg-[#fbfbfb] dark:bg-third no-scrollbar overflow-y-auto`}>
        <Providers>
          <Suspense fallback={<Skeleton />}>{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
